### ISSUE TITLE
Invalid state in EDGE and IE .../ other Browsers working

### ISSUE THREAD

**Issue by Werewolve** [alexandrtovmach/react-microsoft-login#38] opened 2020-01-10 17:22 UTC
Hey all,
had problems to get the microsoft-login to run in my react app in IE and EDGE. Both in newest version. 

"react-microsoft-login": "^1.8.5",
"msal": "^1.2.0",

**Steps to reproduce:**
- Start Authentication
- Enter credentials
- Auth processing
- Error

**Actual result:**
`[object Error]: {description: "Invalid state. e16a39a6-7db8-401b-bde7-0eb035846ce0, state expected : null.", errorCode: "invalid_state_error", errorMessage: "Invalid state. e16a39a6-7db8-401b-bde7-0eb035846ce0, state expected : null.", message: "Invalid state. e16a39a6-7db8-401b-bde7-0eb035846ce0, state expected : null.", name: "ClientAuthError"...}
description: "Invalid state. e16a39a6-7db8-401b-bde7-0eb035846ce0, state expected : null."
errorCode: "invalid_state_error"
errorMessage: "Invalid state. e16a39a6-7db8-401b-bde7-0eb035846ce0, state expected : null."
message: "Invalid state. e16a39a6-7db8-401b-bde7-0eb035846ce0, state expected : null."
name: "ClientAuthError"
stack: "ClientAuthError: Invalid state. e16a39a6-7db8-401b-bde7-0eb035846ce0, state expected : null. at e.prototype.saveTokenFromHash (https://domain.de/static/js/2.5bc9b358.chunk.js?_sw-precache=75a3828db20f5b5187b0913cfd9baf9c:2:1262106) at e.prototype.processCallBack (https://domain.de/static/js/2.5bc9b358.chunk.js?_sw-precache=75a3828db20f5b5187b0913cfd9baf9c:2:1250863) at e.prototype.handleRedirectCallback (https://domain.de/static/js/2.5bc9b358.chunk.js?_sw-precache=75a3828db20f5b5187b0913cfd9baf9c:2:1239454) at t.prototype.componentDidMount (https://domain.de/static/js/2.5bc9b358.chunk.js?_sw-precache=75a3828db20f5b5187b0913cfd9baf9c:2:956213) at Nu (https://domain.de/static/js/2.5bc9b358.chunk.js?_sw-precache=75a3828db20f5b5187b0913cfd9baf9c:2:863639) at t.unstable_runWithPriority (https://domain.de/static/js/2.5bc9b358.chunk.js?_sw-precache=75a3828db20f5b5187b0913cfd9baf9c:2:883264) at Ko (https://domain.de/static/js/2.5bc9b358.chunk.js?_sw-precache=75a3828db20f5b5187b0913cfd9baf9c:2:807843) at Iu (https://domain.de/static/js/2.5bc9b358.chunk.js?_sw-precache=75a3828db20f5b5187b0913cfd9baf9c:2:859980) at Eu (https://domain.de/static/js/2.5bc9b358.chunk.js?_sw-precache=75a3828db20f5b5187b0913cfd9baf9c:2:850201) at Anonymous function (https://domain.de/static/js/2.5bc9b358.chunk.js?_sw-precache=75a3828db20f5b5187b0913cfd9baf9c:2:808147)"
__proto__: Object`

**Expected behavior:**
Authentication should work in EDGE and IT aswell.

**Attachments:**

How i use the lib:
`                            <MicrosoftLogin
                                ref={(e) => this.MicrosoftLogin = e}
                                withUserData={true}
                                clientId='XXXX'
                                redirectUri={window.location.href}
                                authCallback={(err, data) => this.responseMicrosoft(err, data)}
                            >
                                <div className='sso-btn btn mt-2'>
                                    <FaMicrosoft />
                                    <span>{LANG.components.sso[type].microsoft}</span>
                                </div>
                            </MicrosoftLogin>`

**Comment by alexandrtovmach** [comment] 2020-01-11 09:59
thank you for report. I'll take a look after my vacation

**Comment by Werewolve** [comment] 2020-01-23 11:59
Any news @alexandrtovmach ? Still on vacation?

**Comment by alexandrtovmach** [comment] 2020-01-23 15:00
@Werewolve thanks for ping. Just tested from my side and can't reproduce your issue in EDGE. Could you record a video with a bug.

**Comment by alexandrtovmach** [comment] 2020-01-23 15:03
IE doesn't supported by demo page so I can't check it

**Comment by alexandrtovmach** [comment] 2020-02-25 11:48
@Werewolve I'm going close this issue, and if someone finds similar problems feel free to reopen

**Closed by alexandrtovmach** 2020-02-25 11:48 UTC
Labels: bug
